version: "3"
services:
        jobsuccessratereport:
                image: "shreyb/gracc-reporting:jobsuccessrate-report_${VERSIONRELEASE}"
                volumes:
                        - ${LOCALLOGDIR}:/var/log
                        - ${CONFIGDIR}:/home/ifmon/gracc-config
                        - /etc/localtime:/etc/localtime
                environment:
                        - START=${YESTERDAY}
                        - END=${TODAY}
                        - MYGID=${MYGID}
                        - MYUID=${MYUID}
                        - VO=${vo}
