version: "3"
services:
        efficiencyreport:
                image: "shreyb/gracc-reporting:efficiency-report_${VERSIONRELEASE}"
                volumes:
                        - ${LOCALLOGDIR}:/var/log
                        - ${CONFIGDIR}:/home/ifmon/fife-config
                        - /etc/localtime:/etc/localtime
                environment:
                        - START=${starttime}
                        - END=${endtime}
                        - MYGID=${MYGID}
                        - MYUID=${MYUID}
                        - VO=${vo}
